### ISSUE TITLE
Media buttons are not working

### ISSUE THREAD

**Issue by resure** [insidegui/PodcastMenu#11]
Checkbox `Don't own media keys` is off, but media keys still don't work (pressing `Play/Pause` leads to launching iTunes). Is there any debug information I can provide you to help resolving this issue?

**Comment by insidegui** [comment]
Yeap, I've noticed that as well. Works sometimes, sometimes don't. I'll check it out when I have some time. Thanks

**Comment by insidegui** [comment]
Have you experienced this problem lately? After the latest macOS update, it seems to have fixed itself...

**Comment by resure** [comment]
Indeed, now it works! Thanks :)
