### ISSUE TITLE
Add skip forward / back buttons to the TouchBar

### ISSUE THREAD

**Issue by chrismetcalf** [insidegui/PodcastMenu#15]
First of all, I freaking love PodcastMenu, and I've been using it almost constantly since I heard about it on the Back to Work podcast.

I was very excited to discover that it works well with the TouchBar on my new MacBook Pro. Would it be possible, in addition to the timeline scrubber currently provided, to get "back 15s" and "forward 30s" buttons added, much like are in the pop-up itself?

**Comment by insidegui** [comment]
I have to check whether this is possible with the current APIs, but if it is I'll definitely implement this. Great idea :)

**Comment by insidegui** [comment]
BTW, do you remember in which episode they mentioned it? I haven't listened to it :)

**Comment by chrismetcalf** [comment]
With help from none other than Merlin Mann himself, I found it. It was actually on "Do By Friday", not B2W, and you were recommended by none other than Max Temkin, the Cards Against Humanity guy: http://dobyfriday.com/19

**Comment by insidegui** [comment]
Ah, yeah, I listened to that one, quite flattering 🤗

**Comment by insidegui** [comment]
I had a look at the APIs and unfortunately this is not currently possible, I will close this issue and reopen it if this becomes possible on future OS updates.
