### ISSUE TITLE
~/Library/Caches pollution

### ISSUE THREAD

**Issue by tghs** [insidegui/PodcastMenu#22]
`~/Library/Caches` is getting used as the image cache, rather than `~/Library/Caches/br.com.guilhermerambo.PodcastMenu` as I'd expect.

**Comment by tghs** [comment]
My fix makes no attempt to clean up the pollution.

I don't think it's safe to automatically try to clear this up. For the users that will actually care about this, they might rather clear this up themselves anyway.

**Comment by insidegui** [comment]
Doesn't macOS automatically clean the caches folder from time to time?

**Comment by tghs** [comment]
Ah great, I think it does actually, going on the directory timestamps in mine.
