### ISSUE TITLE
Issues with speed settings

### ISSUE THREAD

**Issue by joeljfischer** [insidegui/PodcastMenu#3]
On every podcast, if I attempt to turn the speed to > 1x, the sound is okay for a few seconds, then stutters and fails completely. Pressing pause starts it again for a few seconds, then it fails. Returning to 1x speed fixes it every time.

**Comment by insidegui** [comment]
Can you confirm to me that you don't have the same issues when using overcast.fm in Safari? Please test with the same episode on the same machine.

**Comment by NikolaKirev** [comment]
I have the same exact issue.
Using Overcast website in Safari (same machine, same podcast, same episode) works as expected.

**Comment by insidegui** [comment]
I think It's probably related to the processing done to generate the VU Meter, I will take a look.

**Comment by insidegui** [comment]
This is a bug with webkit's implementation of the audio APIs. I will issue an update which turns the VU into a simple animation instead of using the real audio data, until webkit releases an update fixing this bug.
