### ISSUE TITLE
Not Installing

### ISSUE THREAD

**Issue by Pirateboy04** [insidegui/PodcastMenu#32]
When I double click on the app, after downloading, I get an error:
“PodcastMenu” is damaged and can’t be opened. You should move it to the Trash.

**Comment by insidegui** [comment]
Make sure your Security & Privacy settings allow apps from identified developers to be run, not only from the App Store.

<img width="780" alt="gatekeeper" src="https://user-images.githubusercontent.com/67184/29741789-823b8a1e-8a49-11e7-9cc0-1f69b8751d29.png">

**Comment by Pirateboy04** [comment]
I do have it set to allow apps from identified developers. The issue is that it is damaged.

**Comment by insidegui** [comment]
I just downloaded the latest release from [here](https://github.com/insidegui/PodcastMenu/raw/master/Releases/PodcastMenu_v1.3.zip) and it works just fine.

I even ran `spctl` to check the signature and it's ok.

<img width="462" alt="screen shot 2017-08-26 at 18 41 50" src="https://user-images.githubusercontent.com/67184/29745333-3e5f3012-8a8e-11e7-9677-a65e8d04676c.png">

Which version of macOS are you running?

Can you run `spctl` on your .app and check what the output is?

**Comment by Pirateboy04** [comment]
I am running OS X 10.11.6

When I run spctl:
Downloads/PodcastMenu.app: a sealed resource is missing or invalid

**Comment by insidegui** [comment]
There's something wrong with your download, try downloading it again. 

If the problem persists, it's probably something wrong with the software you're using to decompress the zip file, with your network or other software running on your Mac.

If it persists, can you zip the .app you have there and send it to me?

Thanks!
