### ISSUE TITLE
Thank you!!!!

### ISSUE THREAD

**Issue by jasikpark** [insidegui/PodcastMenu#34]
Thank you so much for making this! I've wanted to be able to use my overcast account on my Mac for a while, and this is perfect!

**Comment by insidegui** [comment]
Thanks for your message! I'm glad you like it :)

**Comment by insidegui** [comment]
I'm going to close this since it is not an actual issue. Thanks for your appreciation, if you have any suggestions or bug reports, feel free to open other issues.
