### ISSUE TITLE
Mouse pointer stops moving when PodcastMenu starts

### ISSUE THREAD

**Issue by cdf1982** [insidegui/PodcastMenu#4]
Hi and thanks for this app, I've always wanted something like this!

I have the strangest issue: when I launch PodcastMenu, my mouse pointer freezes in its last position and nothing (including shutting down PodcastMenu via Termina) seems to make it start moving again until I restart; it still registers clic, by the way, but the cursor doesn't move.

I can reproduce it every time :(

**Comment by insidegui** [comment]
I believe this might be related to the way the app is handling the media keys.

Please download and run the special build of PodcastMenu I have attached and tell me if the problem persists.

[PodcastMenu#4.app.zip](https://github.com/insidegui/PodcastMenu/files/264999/PodcastMenu.4.app.zip)

**Comment by cdf1982** [comment]
You were absolutely right, this build works fine for me! Thank you!

**Comment by insidegui** [comment]
Nice. Now I know what's causing It, but I still have to find another way to make iTunes not open when the play/pause media key is pressed 😬

**Comment by insidegui** [comment]
Just released [version 1.2](https://github.com/insidegui/PodcastMenu/raw/master/Releases/PodcastMenu_v1.2.zip) which includes the solution to your problem and many other improvements.

**Comment by cdf1982** [comment]
Thanks!

Cesare Forelli

Inviato da iPhone
