### ISSUE TITLE
App crashes on MacOS High Sierra 10.13.2

### ISSUE THREAD

**Issue by raisiqueira** [insidegui/PodcastMenu#43]
After the update to MacOS 10.13.2, the App crashes on first open.

**Comment by insidegui** [comment]
Can you send me a crash log? I'm not having this issue on 10.13.2

**Comment by raisiqueira** [comment]
restarting the Mac, started working again. 😑

**Comment by insidegui** [comment]
Weird. Let me know if you have any more issues 😬
