### ISSUE TITLE
Entire window is blank if starting up before network connects

### ISSUE THREAD

**Issue by augmentedfourth** [insidegui/PodcastMenu#5]
If PodcastMenu (which I have in my Login Items) starts up before the WiFi connection is established, the entire interface is a blank white box with the Settings gear in the lower-right. I can't get it to do anything at all, and I have to quit PodcastMenu and start it back up again after the network is connected, at which point it works fine.

Maybe PodcastMenu needs an Offline Mode or something if it can't detect an Internet connection on startup?

**Comment by insidegui** [comment]
Good catch, will work on It. To fix It now, you can right-click on the window and choose `Reload` ;)

**Comment by augmentedfourth** [comment]
Actually, in this state, that right-click Reload isn't helping. I still need to quit & restart the app.
