### ISSUE TITLE
"shake mouse pointer to locate" doesn't work when podcastmenu is running

### ISSUE THREAD

**Issue by augmentedfourth** [insidegui/PodcastMenu#6]
![screen shot 2016-07-06 at 5 05 55 pm](https://cloud.githubusercontent.com/assets/538363/16638418/fec844e6-439b-11e6-959a-f8cd517641db.png)

The "shake mouse pointer to locate" option doesn't work while PodcastMenu is running. I don't know why.

**Comment by insidegui** [comment]
Will investigate. Thanks.

**Comment by augmentedfourth** [comment]
Looks like the app "MagicPrefs" has a similar effect on this Accessibility feature, based on some threads I've read.

**Comment by insidegui** [comment]
I fixed it by changing some parameters on `CGEventTapCreate` and filed a radar with Apple ([radar nº 27267361](http://openradar.appspot.com/radar?id=4952786332549120)).
